routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/dev', 'DevController@index')->name('dev');
Route::middleware(['auth'])->group(function () {
    Route::resource('order', 'DeliveryOrderController');
    Route::resource('article', 'ArticleController');
    Route::resource('category', 'CategoryController');
    Route::resource('client', 'ClientController');
    Route::resource('client', 'ClientController');
    Route::resource('product', 'ProductController');
    Route::resource('promotional', 'PromotionalController');
    Route::resource('setting', 'SettingController');
    Route::resource('street', 'StreetController');
    Route::resource('user', 'User\UserController');
    Route::resource('permission', 'User\PermissionController');
    Route::resource('role', 'User\RoleController');
    Route::post('street/set_has_delivery', 'StreetController@setHasDelivery')
        ->name('street.set_has_delivery');
    Route::post('delete-media', 'MediaController@deleteMedia')->name('deleteMedia');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;


class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/User/PermissionController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission as Permission;
use Illuminate\Http\Request;
use Spatie\QueryBuilder\QueryBuilder;
use Spatie\QueryBuilder\AllowedFilter;
use Illuminate\Validation\Rule;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permission = QueryBuilder::for(Permission::class)
            ->allowedFilters(['name', 'id'])
            ->orderBy('id', 'DESC')
            ->paginate(15);

        return view('user.permission.index', compact('permission'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.permission.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateRequest($request);
        Permission::create(['name' => $request->get('name')]);
        return redirect()->route('permission.index');
    }

    /**
     * @param Permission $permission
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Permission $permission)
    {
        return view('user.permission.show', compact('permission'));
    }

    /**
     * @param Permission $permission
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Permission $permission)
    {
        return view('user.permission.edit', compact('permission'));
    }

    /**
     * @param Request $request
     * @param Permission $permission
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Permission $permission)
    {

        \Validator::make($request->all(), [
            'name' => ['required|max:50|min:2|unique:permissions,name',
                Rule::unique('roles')->ignore($permission->id),
            ]
        ]);

        $permission->update($request->except('_token'));
        return redirect()->route('permission.index');
    }


    /**
     * @param $request
     */
    public function validateRequest($request)
    {
        $request->validate([
            'name' => 'required|max:50|min:2|unique:permissions',
        ]);

    }

    /**
     * @param Permission $permission
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Permission $permission)
    {
        $permission->delete();

        return redirect()->route('permission.index');
    }
}

app/Http/Controllers/User/RoleController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role as Role;
use Illuminate\Http\Request;
use Spatie\QueryBuilder\QueryBuilder;
use Spatie\QueryBuilder\AllowedFilter;
use Illuminate\Validation\Rule;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $role = QueryBuilder::for(Role::class)
            ->allowedFilters(['name', 'id'])
            ->orderBy('id', 'DESC')
            ->paginate(15);

        return view('user.role.index', compact('role'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();
        return view('user.role.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:50|min:2|unique:roles,name'
        ]);

        $role = Role::create($request->except('_token', 'permission'));

        if ($request->has('permission')) {
            $permission = $request->get('permission');
            $role->syncPermissions($permission);
        }

        return redirect()->route('role.index');
    }

    /**
     * @param Role $role
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Role $role)
    {
        $perm = ($role->permissions) ? implode(', ', $role->permissions->pluck('name')->toArray()) : '';

        return view('user.role.show', compact('role', 'perm'));
    }

    public function edit(Role $role)
    {
        if ($role->name == 'super-admin') {
            return abort(403);
        }
        $permissions = Permission::all();
        $role_perm = $role->permissions->pluck('name', 'id')->toArray();

        return view('user.role.edit', compact('role', 'permissions', 'role_perm'));
    }

    /**
     * @param Request $request
     * @param Role $role
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Role $role)
    {
        \Validator::make($request->all(), [
            'name' => ['required|max:50|min:2|unique:roles,name',
                Rule::unique('roles')->ignore($role->id),
            ]
        ]);

        $role->update($request->except('_token', 'permission'));

        if ($request->has('permission')) {
            $permission = $request->get('permission');
            $role->syncPermissions($permission);
        } else {
            $role->syncPermissions([]);
        }

        return redirect()->route('role.index');
    }

    /**
     * @param Role $role
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Role $role)
    {
        if ($role->name == 'super-admin') {
            return abort('403');
        }

        $role->delete();

        return redirect()->route('role.index');
    }


    /**
     * @param $request
     */
    public function validateRequest($request)
    {


    }

}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\QueryBuilder\QueryBuilder;
use Spatie\QueryBuilder\AllowedFilter;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = QueryBuilder::for(User::class)
            ->allowedFilters(['name', 'id', 'email'])
            ->orderBy('id', 'DESC')
            ->paginate(15);

        return view('user.user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        $permissions = Permission::all();

        return view('user.user.create', compact('roles', 'permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:50|min:2',
            'email' => 'required|max:50|email|min:2|unique:users,email',
            'password' => 'required| string|min:8|confirmed',
        ]);

        $data = $request->all();

        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => \Hash::make($data['password']),
        ]);

        if ($request->has('roles')) {
            $roles = $request->get('roles');
            $user->syncRoles($roles);
        }

        if ($request->has('permissions')) {
            $user->syncPermissions($request->get('permissions'));
        }

        return redirect()->route('user.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {

        return view('user.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        $permissions = Permission::all();

        return view('user.user.edit', compact('user', 'roles', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        \Validator::make($request->all(), [
            'email' => ['required|max:50|min:2|unique:users,email|email',
                Rule::unique('roles')->ignore($user->id),
            ],
            'name' => ['required|max:50|min:2'],
        ]);

        $data['email'] = $request->get('email');
        $data['name'] = $request->get('name');

        if ($request->has('password') && $request->get('password') != '') {
            $request->validate([
                'password' => 'required|string|min:8|confirmed'
            ]);
            $data['password'] = \Hash::make($request->get('password'));
        }

        $user->update($data);

        if ($request->has('roles')) {
            $roles = $request->get('roles');
            $user->syncRoles($roles);
        }else{
            $user->syncRoles([]);

        }

        if ($request->has('permissions')) {
            $user->syncPermissions($request->get('permissions'));
        }else{
            $user->syncPermissions([]);

        }

        return redirect()->route('user.index');
    }

    /**
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse|void
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        if ($user->hasRole('super-admin')) {
            return abort(403);
        }

        $user->delete();

        return redirect()->route('user.index');
    }
}

resources/views/user/user/create.blade.php
@extends('layouts.app')

@section('title')
    Создание  пользователя
@endsection

@section('content')
    <div class="content-m-t">
        {!! Form::open()->route('user.store')->post() !!}
        {!! Form::text('name', 'Имя') !!}
        {!! Form::text('email', 'Email') !!}

        {!! Form::text('password', 'Пароль') !!}
        {!! Form::text('password_confirmation', 'Повтор пароля') !!}


        <div class="form-group row">
            <label for="role" class="col-sm-2 col-form-label">
                Роли
            </label>

            <div class="col-sm-6">
                <div class="row">
                    @foreach($roles as $role)
                        <div class="col-sm-12">
                            <input type="checkbox" id="role-{{$role->id}}"
                                   name="roles[]" value="{{$role->name}}">
                            <label for="role-{{$role->id}}">{{$role->name}}</label>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>


        <div class="form-group row">
            <label for="permission" class="col-sm-2 col-form-label">Доп. разрешения</label>
            <div class="col-sm-6">
                <div class="row">
                    @foreach($permissions as $permission)
                        <div class="col-sm-3">
                            <input type="checkbox" id="permission-{{$permission->id}}"
                                   name="permissions[]" value="{{$permission->name}}">
                            <label for="permission-{{$permission->id}}">{{$permission->name}}</label>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>


        <div class="form-group row">
            <div class="offset-2 col-sm-10">
                {!! Form::submit('Сохранить изменения') !!}
            </div>
        </div>
        {!!  Form::close() !!}
    </div>
@endsection

@section('actions')

@endsection

resources/views/user/user/edit.blade.php
@extends('layouts.app')

@section('title')
    Редактирование роли
@endsection

@section('content')
    <div class="content-m-t">

        {!! Form::open()->route('user.update', ['user' => $user->id])->put()->fill($user) !!}
        {!! Form::text('name', 'Имя') !!}
        {!! Form::text('email', 'Email') !!}

        {!! Form::text('password', 'Пароль') !!}
        {!! Form::text('password_confirmation', 'Повтор пароля') !!}


        <div class="form-group row">
            <label for="role" class="col-sm-2 col-form-label">
                Роли
            </label>

            <div class="col-sm-6">
                <div class="row">
                    @foreach($roles as $role)
                        <div class="col-sm-12">
                            <input type="checkbox" id="role-{{$role->id}}"
                                   @if($user->hasRole($role->name))
                                   checked
                                   @endif
                                   name="roles[]" value="{{$role->name}}">
                            <label for="role-{{$role->id}}">{{$role->name}}</label>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label for="permission" class="col-sm-2 col-form-label">Разрешения</label>
            <div class="col-sm-6">
                <div class="row">
                    @foreach($permissions as $permission)
                        <div class="col-sm-3">
                            <input type="checkbox" id="permission-{{$permission->id}}"
                                   @if($user->hasPermissionTo($permission->name))
                                   checked
                                   @endif
                                   name="permissions[]" value="{{$permission->name}}">
                            <label for="permission-{{$permission->id}}">{{$permission->name}}</label>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-2 col-sm-10">
                {!! Form::submit('Сохранить изменения') !!}
            </div>
        </div>
        {!!  Form::close() !!}
    </div>
@endsection

@section('actions')

@endsection

resources/views/user/user/index.blade.php
@extends('layouts.app')

@section('title')
    Пользователи
@endsection

@section('content')
    <div class="table-responsive">
        <table id="grid-table" class="table  table-hover table-striped">
            <thead>
            <tr>
                <th scope="col">#ID</th>
                <th scope="col">Имя</th>
                <th scope="col">Email</th>
                <th scope="col">Роли</th>
                <th scope="col">Разрешения</th>
                <th scope="col">Дата обновления</th>
                <th scope="col">Дата создания</th>
            </tr>
            </thead>
            <tbody>
            @foreach($user as $c)
                <tr url="{{route('user.show',['user' => $c->id])}}">
                    <td>{{$c->id}}</td>
                    <td>{{$c->name}}</td>
                    <td>{{$c->email}}</td>
                    <td>
                        {{($c->roles) ? implode(', ', $c->roles->pluck('name')->toArray()) : ''}}
                    </td>
                    <td>
                        @if(!$c->hasRole('super-admin'))
                            {{($c->getDirectPermissions()) ? implode(', ', $c->getDirectPermissions()->pluck('name')->toArray()) : ''}}
                        @endif
                    </td>
                    <td>{{$c->updated_at->format('H:i m.d.Y')}}</td>
                    <td>{{$c->created_at->format('H:i m.d.Y')}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $user->links() }}
    </div>
@endsection


@section('actions')
    <div class="btn-toolbar mb-2 mb-md-0">
        @add(['route' => route('user.create')])
    </div>
@endsection

@push('css')

@endpush

resources/views/user/user/show.blade.php
@extends('layouts.app')

@section('title')
    Роль
@endsection

@section('content')
    <div class="show-model">
        <dl class="row">
            <dt class="col-sm-2">
                Имя
            </dt>
            <dd class="col-sm-10">
                {{$user->name}}
            </dd>
        </dl>

        <dl class="row">
            <dt class="col-sm-2">
                Email
            </dt>
            <dd class="col-sm-10">
                {{$user->email}}
            </dd>
        </dl>

        <dl class="row">
            <dt class="col-sm-2">
                Роли
            </dt>
            <dd class="col-sm-10">
                {{($user->roles) ? implode(', ', $user->roles->pluck('name')->toArray()) : ''}}
            </dd>
        </dl>

        @if(!$user->hasRole('super-admin'))
            <dl class="row">
                <dt class="col-sm-2">
                    Разрешения
                </dt>
                <dd class="col-sm-10">
                    {{($user->getDirectPermissions()) ? implode(', ', $user->getDirectPermissions()->pluck('name')->toArray()) : ''}}
                </dd>
            </dl>
        @endif

    </div>
@endsection

@section('actions')
    @edit(['route' => route('user.edit',['user' => $user->id])])&nbsp;
    @delete(['route' => route('user.destroy',['user' => $user->id])])
@endsection