routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/dev', 'DevController@index')->name('dev');
Route::middleware(['auth'])->group(function () {
    Route::resource('order', 'DeliveryOrderController');
    Route::resource('article', 'ArticleController');
    Route::resource('category', 'CategoryController');
    Route::resource('client', 'ClientController');
    Route::resource('client', 'ClientController');
    Route::resource('product', 'ProductController');
    Route::resource('promotional', 'PromotionalController');
    Route::resource('setting', 'SettingController');
    Route::resource('street', 'StreetController');
    Route::resource('user', 'User\UserController');
    Route::resource('permission', 'User\PermissionController');
    Route::resource('role', 'User\RoleController');
    Route::post('street/set_has_delivery', 'StreetController@setHasDelivery')
        ->name('street.set_has_delivery');
    Route::post('delete-media', 'MediaController@deleteMedia')->name('deleteMedia');

});

app/Models/Street.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Street extends Model
{
    protected $guarded = ['id'];

    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];
}

app/Http/Controllers/StreetController.php
<?php

namespace App\Http\Controllers;

use App\Models\Street;
use Illuminate\Http\Request;

use Spatie\QueryBuilder\QueryBuilder;
use Spatie\QueryBuilder\AllowedFilter;

class StreetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $street = QueryBuilder::for(Street::class)
            ->allowedFilters(['name', 'id'])
            ->orderBy('id', 'DESC')
            ->paginate(15);

        return view('street.index', compact('street'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('street.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateRequest($request);

        street::create($request->except('_token'));

        return redirect()->route('street.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Street $street
     * @return \Illuminate\Http\Response
     */
    public function show(Street $street)
    {
        return view('street.show', compact('street'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Street $street
     * @return \Illuminate\Http\Response
     */
    public function edit(Street $street)
    {
        return view('street.edit', compact('street'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Street $street
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Street $street)
    {
        $this->validateRequest($request);
        $street->update($request->except('_token'));
        return redirect()->route('street.index');
    }

    /**
     * @param Street $street
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Street $street)
    {
        $street->delete();

        return redirect()->route('street.index');
    }

    /**
     * @param $request
     */
    public function validateRequest($request)
    {
        $request->validate([
            'name' => 'required|max:255',
        ]);

    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function setHasDelivery(Request $request)
    {
        $request->validate([
            'street_id' => 'required|integer',
        ]);

        $street = Street::findOrFail($request->get('street_id'));
        $has_delivery = ($street->has_delivery) ? 0 : 1;

        $street->update([
            'has_delivery' => $has_delivery
        ]);

        return response()->json([
            'status' => 'success',
        ]);

    }
}

resources/views/street/create.blade.php
@extends('layouts.app')

@section('title')
    Создание улицы
@endsection

@section('content')
    <div class="content-m-t">
        {!! Form::open()->route('street.store')->post() !!}
        {!! Form::text('name', 'Наименование') !!}
        {!! Form::select('has_delivery', 'Доставка',[0 => 'Нет', 1 => 'Да']) !!}
        <div class="form-group row">
            <div class="offset-2 col-sm-10">
                {!! Form::submit('Сохранить изменения') !!}
            </div>
        </div>
        {!!  Form::close() !!}
    </div>
@endsection

@section('actions')

@endsection

resources/views/street/edit.blade.php
@extends('layouts.app')

@section('title')
    Редактирование улицы
@endsection

@section('content')
    <div class="content-m-t">
        {!! Form::open()->route('street.update', ['street' => $street->id])->put()->fill($street) !!}
        {!! Form::text('name', 'Наименование') !!}
        {!! Form::select('has_delivery', 'Доставка',[0 => 'Нет', 1 => 'Да']) !!}
        <div class="form-group row">
            <div class="offset-2 col-sm-10">
                {!! Form::submit('Сохранить изменения') !!}
            </div>
        </div>
        {!!  Form::close() !!}
    </div>
@endsection

@section('actions')

@endsection

resources/views/street/index.blade.php
@extends('layouts.app')

@section('title')
    Улицы
@endsection

@section('content')
    <div class="table-responsive">
        <table id="grid-table" class="table  table-hover table-striped">
            <thead>
            <tr>
                <th scope="col">#ID</th>
                <th scope="col">Наименование</th>
                <th scope="col">Доставка</th>
                <th scope="col">Дата обновления</th>
                <th scope="col">Дата создания</th>
            </tr>
            </thead>
            <tbody>
            @foreach($street as $a)
                <tr url="{{route('street.show',['street' => $a->id])}}">
                    <td>{{$a->id}}</td>
                    <td>{{$a->name}}</td>
                    <td>
                        <input class="has_delivery" type="checkbox" @if($a->has_delivery) checked @endif
                        value="{{$a->id}}">
                    </td>
                    <td>{{$a->updated_at->format('H:i m.d.Y')}}</td>
                    <td>{{$a->created_at->format('H:i m.d.Y')}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $street->links() }}
    </div>
@endsection

@section('actions')
    <div class="btn-toolbar mb-2 mb-md-0">
        @add(['route' => route('street.create')])
    </div>
@endsection

@push('css')

@endpush

@push('scripts')
    <script>
        $(function () {
            $('#grid-table .has_delivery').on('change', function (e) {
                $.ajax({
                    data: {
                        'street_id': $(this).attr('value'),
                        '_token': '{{csrf_token()}}'
                    },
                    url: '{{route('street.set_has_delivery')}}',
                    type: 'POST',
                    dataType: 'JSON'
                });
                e.preventDefault();
            });
        });
    </script>
@endpush

resources/views/street/show.blade.php
@extends('layouts.app')

@section('title')
    Улица
@endsection

@section('content')
    <div class="show-model">
        <dl class="row">
            <dt class="col-sm-2">
                Наименование
            </dt>
            <dd class="col-sm-10">
                {{$street->name}}
            </dd>
        </dl>

        <dl class="row">
            <dt class="col-sm-2">
                Доставка
            </dt>
            <dd class="col-sm-10">
                @if($street->has_delivery)
                    <span class="badge badge-primary">Да</span>
                @else
                    <span class="badge badge-secondary">Нет</span>
                @endif
            </dd>
        </dl>

    </div>
@endsection

@section('actions')
    @edit(['route' => route('street.edit',['street' => $street->id])])&nbsp;
    @delete(['route' => route('street.destroy',['street' => $street->id])])
@endsection